export default {
  SET_DOG_LIST: 'SET_DOG_LIST',
  ADD_DOG_LIST: 'ADD_DOG_LIST',
  SET_BREEDS: 'SET_BREEDS',
  SET_BREED_IMAGE_LIST: 'SET_BREED_IMAGE_LIST',
  DELETE_BREED_IMAGE_LIST: 'DELETE_BREED_IMAGE_LIST',
  SET_LIKE: 'SET_LIKE',
  SET_LIKES: 'SET_LIKES',
  UNSET_LIKE: 'UNSET_LIKE'
}
